// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6XdfeclcVsvV8qAOgg_LyHXB1neELiEo',
    appId: '1:530467491766:web:488b8d4dc8e2e5169b3b17',
    messagingSenderId: '530467491766',
    projectId: 'calai-11be1',
    authDomain: 'calai-11be1.firebaseapp.com',
    storageBucket: 'calai-11be1.firebasestorage.app',
    measurementId: 'G-V7YPQEW5X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4KVObqa466x4EisRrtEjVbBx--jhV2xE',
    appId: '1:530467491766:android:9699fa4a0420d9319b3b17',
    messagingSenderId: '530467491766',
    projectId: 'calai-11be1',
    storageBucket: 'calai-11be1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa-tJ8bkXyUcW98-riF_WP3TSOdbvvm6Q',
    appId: '1:530467491766:ios:019aa29d8be1e8289b3b17',
    messagingSenderId: '530467491766',
    projectId: 'calai-11be1',
    storageBucket: 'calai-11be1.firebasestorage.app',
    androidClientId: '530467491766-rpoclgct9o8ekbsuukvscbnv7ou5ipkr.apps.googleusercontent.com',
    iosClientId: '530467491766-53nb81qnsc5eds4eb0mbot0m0jrpin0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.calai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa-tJ8bkXyUcW98-riF_WP3TSOdbvvm6Q',
    appId: '1:530467491766:ios:019aa29d8be1e8289b3b17',
    messagingSenderId: '530467491766',
    projectId: 'calai-11be1',
    storageBucket: 'calai-11be1.firebasestorage.app',
    androidClientId: '530467491766-rpoclgct9o8ekbsuukvscbnv7ou5ipkr.apps.googleusercontent.com',
    iosClientId: '530467491766-53nb81qnsc5eds4eb0mbot0m0jrpin0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.calai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6XdfeclcVsvV8qAOgg_LyHXB1neELiEo',
    appId: '1:530467491766:web:1f4e8103e74f6cd99b3b17',
    messagingSenderId: '530467491766',
    projectId: 'calai-11be1',
    authDomain: 'calai-11be1.firebaseapp.com',
    storageBucket: 'calai-11be1.firebasestorage.app',
    measurementId: 'G-TB11EG4QTD',
  );

}