import 'dart:async';

import 'package:calai/onboarding/app_entry.dart';
import 'package:calai/providers/health_provider.dart';
import 'package:calai/widgets/debug/debug_overlay.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:home_widget/home_widget.dart';
import 'package:calai/pages/home/floating_grid/food_database/food_database.dart';

import 'package:calai/theme/app_theme.dart';
import 'package:calai/theme/theme_service.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'firebase_options.dart'; // This file was generated by the CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load theme settings before app launch
  final themeService = ThemeService();
  final savedTheme = await themeService.loadTheme();
  final initialThemeMode = _getThemeMode(savedTheme);
  final sharedPrefs = await SharedPreferences.getInstance();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // await initializeGoogleSignIn(); // 👈 REQUIRED

  runApp(ProviderScope(overrides: [
    // 2. Override the provider with the actual instance
    sharedPreferencesProvider.overrideWithValue(sharedPrefs),
  ],child: MyApp(initialThemeMode: initialThemeMode)));
}

/// Maps saved string theme to Flutter [ThemeMode]
ThemeMode _getThemeMode(String theme) {
  switch (theme) {
    case 'Light':
      return ThemeMode.light;
    case 'Dark':
      return ThemeMode.dark;
    case 'Automatic':
      return ThemeMode.system;
    default:
      return ThemeMode.light;
  }
}

class MyApp extends StatefulWidget {
  final ThemeMode initialThemeMode;

  const MyApp({super.key, required this.initialThemeMode});

  @override
  State<MyApp> createState() => _MyAppState();

  /// Static helper to access theme switching logic from child widgets
  static _MyAppState? of(BuildContext context) =>
      context.findAncestorStateOfType<_MyAppState>();
}

class _MyAppState extends State<MyApp> {
  late ThemeMode _themeMode;
  final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();
  StreamSubscription<Uri?>? _widgetClickSubscription;

  @override
  void initState() {
    super.initState();
    _themeMode = widget.initialThemeMode;
    _initHomeWidgetActions();
  }

  void _initHomeWidgetActions() {
    HomeWidget.initiallyLaunchedFromHomeWidget().then(_handleWidgetUri);
    _widgetClickSubscription = HomeWidget.widgetClicked.listen(_handleWidgetUri);
  }

  void _handleWidgetUri(Uri? uri) {
    if (uri == null) return;
    final navigator = _navigatorKey.currentState;
    if (navigator == null) {
      WidgetsBinding.instance.addPostFrameCallback((_) => _handleWidgetUri(uri));
      return;
    }

    final destination = uri.host.isNotEmpty
        ? uri.host
        : uri.path.replaceFirst('/', '');
    final normalized = destination.replaceAll('-', '_');

    if (destination == 'food-database' ||
        normalized == 'food_database' ||
        uri.path.contains('food_database')) {
      navigator.push(
        MaterialPageRoute(
          builder: (_) => const FoodDatabasePage(),
        ),
      );
    }
  }

  @override
  void dispose() {
    _widgetClickSubscription?.cancel();
    super.dispose();
  }

  /// Sets the application's theme mode and triggers a rebuild
  void setThemeMode(ThemeMode mode) {
    if (_themeMode != mode) {
      setState(() => _themeMode = mode);
    }
  }

  // @override
  // Widget build(BuildContext context) {
  //   return MaterialApp(
  //     title: 'Cal AI - Calorie Tracker',
  //     debugShowCheckedModeBanner: false,
  //     themeMode: _themeMode,
  //     theme: AppTheme.lightTheme,
  //     darkTheme: AppTheme.darkTheme,
  //     home: const AppEntry(),
  //   );
  // }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cal AI - Calorie Tracker',
      debugShowCheckedModeBanner: false,
      navigatorKey: _navigatorKey,
      themeMode: _themeMode,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,

      // ✅ GLOBAL OVERLAY INJECTION
      builder: (context, child) {
        // We wrap the entire app in a Stack
        return Stack(
          children: [
            // 1. The actual screen (AppEntry, Dashboard, etc.)
            if (child != null) child,

            // 2. The Debug Overlay (Only show in Debug Mode)
            if (kDebugMode)
              const Positioned(
                right: 0,
                top: 100, // Adjust start position so it doesn't block AppBar
                child: DebugOverlay(),
              ),
          ],
        );
      },

      home: const AppEntry(),
    );
  }
}
